model_name: 'q-lr90'
problem:
  gamma: 0.99  # discounting factor
training:
  nb_epochs: 100000
  learning_rate: 0.90  # alpha
  print_score: 500  # each 500 episodes
  print_window_size:  100
  exploration:
    name: 'Boltzmann'
    clip: [-500, 500]
testing:
  nb_epochs: 10000